### ISSUE TITLE
Do you have a plan to create Pt.3

### ISSUE THREAD

**Issue by MrDoLoop** [mzgreen/HideOnScrollExample#3]
Hi, 
Thanks for your great effort.I have learnt a lot by following your post and demo projects. Do you have a plan for the next chapter? I think adding "viewpager" should be a good issues to continue, just like google play app does. Top: toolbar+stripes. Below: viewpage within different fragments.

Waitting for your opinion. Thanks a lot in advanced.

**Comment by mzgreen** [comment]
Hi :)
Many people asks for it so I do plan it but I can't tell you when because I really don't know. I have a couple of ideas for upcoming posts so I will definitely continue writing.
