### ISSUE TITLE
Scrolling fast multiple time when the animation happends will desync everything.

### ISSUE THREAD

**Issue by Wolftein** [mzgreen/HideOnScrollExample#5]
https://www.youtube.com/watch?v=ahzYlOcHI0k

**Comment by mzgreen** [comment]
Did you try to reproduce it on demo app? I couldn't do it.

**Comment by mariolope10** [comment]
I have the same problem with demo app.

**Comment by mzgreen** [comment]
This tutorial is slightly outdated as there is Android Design Support Library.
