### ISSUE TITLE
Scrolling to the end then scrolling up and down fast don't work as expected

### ISSUE THREAD

**Issue by YuriHeupa** [mzgreen/HideOnScrollExample#6]
I found this bug on the example code. You can reproduce with the following steps:
Scroll to the end of the list > Scroll a little up then scroll down fast > The toolbar stay half visible and the list is at the end (BUG) > If you scroll up again the toolbar snap to the hide state

I've take a video showing this:
https://www.youtube.com/watch?v=KyxTgzg4Z4o

**Comment by mzgreen** [comment]
It's now fixed by using CoordinatorLayout from Design Support Library.
